///////////////////////////////////////////////////////////
//  AddingInformation.cs
//  Implementation of the Class <<control>> AddingInformation
//  Generated by Enterprise Architect
//  Created on:      23-май-2018 12:50:30
//  Original author: Veronika
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data.SQLite;

namespace UniversitySite {
	/// <summary>
	/// Добавление информации в банк данных
	/// </summary>
	public class  AddingInformation {
        /// 
        /// <param name="item"></param>
        public bool addAddress(string item){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public bool addDepartment(string item){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public bool addFaculty(string item){

			return false;
		}

		/// 
		/// <param name="form"></param>
		public bool addForm(FormOfEducation form){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public bool addHead(Head item){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public bool addPhone(string item){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public bool addSpeciality(string item){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public bool addWebsite(string item){

			return false;
		}

	}//end <<control>> AddingInformation

}//end namespace ManageInfoClassDiagram