///////////////////////////////////////////////////////////
//  AddingInformation.cs
//  Implementation of the Class <<control>> AddingInformation
//  Generated by Enterprise Architect
//  Created on:      23-май-2018 12:50:30
//  Original author: Veronika
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data.SQLite;

namespace UniversitySite {
	/// <summary>
	/// Добавление информации в банк данных
	/// </summary>
	public static class  AddingInformation {

        public static bool AddInfo(Department dep, Speciality spec, Faculty fac,Head head, string address, string phone, string site, int year, FormOfEducation form)
        {
            if (dep != null)
                AddDepartment(dep);
            if (head != null)
                AddHead(head);
            if (address.Length != 0)
                AddAddress(address);
            if (phone.Length != 0)
                AddPhone(phone);
            if (site.Length != 0)
                AddWebsite(site);
            AddForm(form);

            return AddForm(form);
        }


        /// 
        /// <param name="item"></param>
        public static bool AddAddress(string item){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public static bool AddDepartment(Department item){
            
			return false;
		}

		/// 
		/// <param name="item"></param>
		public static bool AddFaculty(Faculty item){

			return false;
		}

		/// 
		/// <param name="form"></param>
		public static bool AddForm(FormOfEducation form){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public static bool AddHead(Head item){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public static bool AddPhone(string item){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public static bool AddSpeciality(Speciality item){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public static bool AddWebsite(string item){

			return false;
		}

	}//end <<control>> AddingInformation

}//end namespace ManageInfoClassDiagram