///////////////////////////////////////////////////////////
//  CheckingInfo.cs
//  Implementation of the Class CheckingInfo
//  Generated by Enterprise Architect
//  Created on:      23-май-2018 13:54:01
//  Original author: Veronika
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace UniversitySite {
	/// <summary>
	/// Проверка введенной информации
	/// </summary>
	public static class CheckingInfo {

        /// 
        /// <param name="userType">Type of user</param>
        /// <param name="reqType">Type of request</param>
        public static bool CheckAccess(TypeOfUser userType, TypeOfRequest reqType){
            if (reqType == TypeOfRequest.addInfo && userType == TypeOfUser.administrator)
                return true;
            if (reqType == TypeOfRequest.updateInfo && userType == TypeOfUser.university_worker)
                return true;
            if (reqType == TypeOfRequest.getInfo)
                return true;

            return false;
		}

		/// 
		/// <param name="info">Info for checking</param>
		public static bool CheckCorectness(string info){
            int year = 0;
            try
            {
                year = Int32.Parse(info);
            }
            catch(Exception ex)
            {
                return false;
            }
           return year > 1950 && year < 2019;
		}

	}//end <<control>> CheckingInfo

}