///////////////////////////////////////////////////////////
//  CheckingInfo.cs
//  Implementation of the Class CheckingInfo
//  Generated by Enterprise Architect
//  Created on:      23-май-2018 13:54:01
//  Original author: Veronika
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace UniversitySite {
	/// <summary>
	/// Проверка введенной информации
	/// </summary>
	public class CheckingInfo {

		/// 
		/// <param name="username"></param>
		public bool CheckAccess(string username){

			return false;
		}

		/// 
		/// <param name="info"></param>
		public bool CheckCorectness(string info){

			return false;
		}

	}//end <<control>> CheckingInfo

}