///////////////////////////////////////////////////////////
//  LoginController.cs
//  Implementation of the Class <<controller>> LoginController
//  Generated by Enterprise Architect
//  Created on:      23-май-2018 13:49:22
//  Original author: Veronika
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data.SQLite;
using System.Data;

namespace UniversitySite {
	public static class  LoginController {
        static SQLiteConnection m_dbConn;
        static SQLiteCommand m_sqlCmd;

        private static void ConnectDB()
        {
            m_dbConn = new SQLiteConnection();
            m_sqlCmd = new SQLiteCommand();

            try
            {
                m_dbConn = new SQLiteConnection("Data Source= UniverInfo.db;Version=3;");
                m_dbConn.Open();
                m_sqlCmd.Connection = m_dbConn;
            }
            catch (SQLiteException ex)
            {
                
            }
        }
		/// 
		/// <param name="login"></param>
		private static bool CheckLogin(string login){
            int maxLen = 20;

            return (login.Length != 0 && login.Length <= maxLen);
		}

		/// 
		/// <param name="password"></param>
		private static bool CheckPassword(string password){
            int maxLen = 20;

            return (password.Length != 0 && password.Length <= maxLen);
        }

		public static User MakeUser(string login, string password){
            ConnectDB();
            
            String sqlQuery;
            User user = null;

            try
            {
                if (CheckLogin(login) && CheckPassword(password))
                {
                    sqlQuery = "SELECT TypeID FROM USER WHERE LOGIN = " + login;
                    sqlQuery += " AND PASSWORD= " + password;

                    m_sqlCmd.CommandText = sqlQuery;
                    var reader = m_sqlCmd.ExecuteReader();

                    String str = "";
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                            str = reader.GetString(0);
                    }

                    int type = Int32.Parse(str);

                    user = new User(login, password, type);
                    return user;
                  
                }
            }
            catch (SQLiteException ex)
            {
            }
            return user;
		}

	}//end <<controller>> LoginController

}//end namespace LoginClassDiagram