///////////////////////////////////////////////////////////
//  ProcessingSystem.cs
//  Implementation of the Class <<control>> ProcessingSystem
//  Generated by Enterprise Architect
//  Created on:      23-май-2018 13:53:58
//  Original author: Veronika
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data.SQLite;


using RequestClassDiagram;
namespace RequestClassDiagram {
	/// <summary>
	/// Обработка запросов
	/// </summary>
	public class ProcessingSystem {
        
		/// 
		/// <param name="info"></param>
		public bool AddInfo(string info){

			return false;
		}

		/// 
		/// <param name="info"></param>
		public bool ChangeInfo(string info){

			return false;
		}

		/// 
		/// <param name="info"></param>
		public bool CheckInfo(string info){

			return false;
		}

		/// 
		/// <param name="info"></param>
		public string FindInfo(string info){

			return "";
		}

	}//end <<control>> ProcessingSystem

}//end namespace RequestClassDiagram