///////////////////////////////////////////////////////////
//  UpdatingInformation.cs
//  Implementation of the Class <<control>> UpdatingInformation
//  Generated by Enterprise Architect
//  Created on:      23-май-2018 12:50:35
//  Original author: Veronika
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace UniversitySite {
	/// <summary>
	/// Обновление информации в банке данных
	/// </summary>
	public class  UpdatingInformation {

		/// 
		/// <param name="item"></param>
		public bool updateHistory(Head item){

			return false;
		}

        /// 
        /// <param name="subject"></param>
        public bool updateSubjects(string subject)
        {
            return false;
        }

        /// 
        /// <param name="score"></param>
        public bool updateMaxScore(double score){

			return false;
		}

		/// 
		/// <param name="item"></param>
		public bool updatePlanOfAdmission(string item){

			return false;
		}

	}//end <<control>> UpdatingInformation

}//end namespace ManageInfoClassDiagram